name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync --all-packages --group dev --frozen
      - run: uv run ruff format --check .
      - run: uv run ruff check .
      - run: uv run mypy packages/labtasker-client/src packages/labtasker-server/src
      - run: uv run pytest
      - run: uv build --all-packages
